global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080' # ingestion-service
          - 'host.docker.internal:8081' # processor-service
          - 'host.docker.internal:8082' # alert-service
          - 'host.docker.internal:8083' # sink-service
          - 'host.docker.internal:8084' # gateway
